# Generated by Django 2.2.4 on 2019-10-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190916_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctgfeature',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AddField(
            model_name='ctgfeature',
            name='extended',
            field=models.CharField(max_length=8, null=True, verbose_name='Extended Only'),
        ),
    ]
