# Generated by Django 2.2.4 on 2019-10-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191003_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctgrestriction',
            name='rule_type',
            field=models.CharField(choices=[('MAX', 'Maximum Value'), ('MIN', 'Minimum Value'), ('UPLEN', 'Length Upper Limit'), ('LOLEN', 'Length Lower Limit'), ('AO', 'Alphabetical Letters Only'), ('NUO', 'Numbers Only'), ('EML', 'Email Format'), ('NN', 'Not Null')], max_length=32, verbose_name='Rule Type'),
        ),
    ]
