# Generated by Django 2.2.4 on 2019-10-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191016_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctgprice',
            name='ctg_doc_id',
        ),
        migrations.AddField(
            model_name='ctgprice',
            name='specification',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.CtgSpecification'),
            preserve_default=False,
        ),
    ]
