# Generated by Django 2.2.4 on 2019-11-30 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191026_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctgfeature',
            name='ctg_doc_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Catalog Object ID'),
        ),
        migrations.AlterField(
            model_name='ctgproduct',
            name='ctg_doc_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Catalog Object ID'),
        ),
        migrations.AlterField(
            model_name='ctgspecification',
            name='ctg_doc_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Catalog Object ID'),
        ),
    ]
