-- Get all products from an order/site
SELECT PBI.BASKET_ITEM_ID, POI.ORDER_NAME, PS.SITE_NAME, PBI.ITEMCODE, PBI.SERIAL FROM PTA_ORDER_INSTANCE POI
INNER JOIN PTA_SITE PS ON POI.ORDER_INSTANCE_ID = PS.ORDER_INSTANCE_ID
INNER JOIN PTA_BASKET_ITEM PBI ON POI.BASKET_ID = PBI.BASKET_ID AND PS.PTA_SITE_ID = PBI.PTA_SITE_ID
WHERE 1 = 1
--AND PS.PTA_SITE_ID = ''
AND POI.ORDER_NUMBER = 'a2f72ac7751e4cffbd1d2ad556fb51c8'
ORDER BY PS.CREATION_TIME DESC, PBI.SERIAL ASC;

-- Catalog product matrix view
SELECT PR.ITEMCODE, PR.NAME, SPEC.LEAF_NAME, SPEC.LABEL, SPEC.DATA_TYPE, SPEC.DEFAULT_VALUE,
VAL.CODE, VAL.TRANSLATION, RES.RULE_TYPE, RES.VALUE, PRI.MRC, PRI.NRC, PRI.UNIT_MRC, PRI.UNIT_NRC
FROM CTG_PRODUCT PR
INNER JOIN UNO_CLIENT UC ON PR.CLIENT_ID = UC.CLIENT_ID
INNER JOIN CTG_SPECIFICATION SPEC ON PR.CTG_DOC_ID = SPEC.PARENT_CTG_ID
LEFT JOIN CTG_VALUE VAL ON SPEC.SPECIFICATION_ID = VAL.SPECIFICATION_ID
LEFT JOIN CTG_RESTRICTION RES ON SPEC.SPECIFICATION_ID = RES.SPECIFICATION_ID
LEFT JOIN CTG_PRICE PRI ON (SPEC.SPECIFICATION_ID = PRI.SPECIFICATION_ID AND SPEC.DATA_TYPE <> 'ENUM') OR (VAL.VALUE_ID = PRI.VALUE_ID)
WHERE PR.ACTIVE = 1
AND SPEC.ACTIVE = 1
AND UPPER(UC.CTG_NAME) = 'SPC'
ORDER BY PR.ITEMCODE, SPEC.LEAF_NAME, VAL.CODE;

-- Catalog feature matrix view
SELECT FET.ITEMCODE, FET.NAME, SPEC.LEAF_NAME, SPEC.LABEL, SPEC.DATA_TYPE, SPEC.DEFAULT_VALUE,
VAL.CODE, VAL.TRANSLATION, RES.RULE_TYPE, RES.VALUE, PRI.MRC, PRI.NRC, PRI.UNIT_MRC, PRI.UNIT_NRC
FROM CTG_PRODUCT PR
INNER JOIN CTG_FEATURE FET ON PR.PRODUCT_ID = FET.PRODUCT_ID
INNER JOIN CTG_SPECIFICATION SPEC ON FET.CTG_DOC_ID = SPEC.PARENT_CTG_ID
LEFT JOIN CTG_VALUE VAL ON SPEC.SPECIFICATION_ID = VAL.SPECIFICATION_ID
LEFT JOIN CTG_RESTRICTION RES ON SPEC.SPECIFICATION_ID = RES.SPECIFICATION_ID
LEFT JOIN CTG_PRICE PRI ON (SPEC.SPECIFICATION_ID = PRI.SPECIFICATION_ID AND SPEC.DATA_TYPE <> 'ENUM') OR (VAL.VALUE_ID = PRI.VALUE_ID)
WHERE PR.ACTIVE = 1
AND PR.ITEMCODE = 'SPC_PR_IOT_FAC'
AND FET.ACTIVE = 1
AND SPEC.ACTIVE = 1
ORDER BY FET.ITEMCODE, SPEC.LEAF_NAME, VAL.CODE;

-- Order items view
SELECT PS.SITE_NAME, PBI.ITEMCODE, PBI.SERIAL, PBI.IS_VALID, PIL.LEAF_NAME, PIL.LEAF_VALUE
FROM PTA_ORDER_INSTANCE POI
INNER JOIN PTA_BASKET_ITEM PBI ON POI.BASKET_ID = PBI.BASKET_ID
INNER JOIN PTA_SITE PS ON PBI.PTA_SITE_ID = PS.PTA_SITE_ID
LEFT JOIN PTA_ITEM_LEAF PIL ON PBI.BASKET_ITEM_ID = PIL.BASKET_ITEM_ID
WHERE POI.ORDER_NUMBER = '9a19fcaf1b1d424a8efa57dd7f13f19d'
--AND PS.SITE_NAME = ''
--AND PBI.PARENT_ID IS NULL
--AND PBI.PARENT_ID IS NOT NULL
--AND PBI.ITEMCODE = ''
--AND PBI.BASKET_ITEM_ID = '6c75b0ac5e6143ecb6434699975a0c24'
AND (PBI.BASKET_ITEM_ID = 'fd20d0913e2a40e698aafd3aa427e781' OR PBI.PARENT_ID = 'fd20d0913e2a40e698aafd3aa427e781')
--AND PIL.LEAF_NAME = ''
ORDER BY PS.SITE_NAME, PBI.SERIAL, PBI.ITEMCODE;