-- Get all products from an order/site
SELECT PBI.BASKET_ITEM_ID, POI.ORDER_NAME, PS.SITE_NAME, PBI.ITEMCODE, PBI.SERIAL FROM PTA_ORDER_INSTANCE POI
INNER JOIN PTA_SITE PS ON POI.ORDER_INSTANCE_ID = PS.ORDER_INSTANCE_ID
INNER JOIN PTA_BASKET_ITEM PBI ON POI.BASKET_ID = PBI.BASKET_ID AND PS.PTA_SITE_ID = PBI.PTA_SITE_ID
WHERE 1 = 1
--AND PS.PTA_SITE_ID = ''
AND POI.ORDER_NUMBER = 'a2f72ac7751e4cffbd1d2ad556fb51c8'
ORDER BY PS.CREATION_TIME DESC, PBI.SERIAL ASC;