# Generated by Django 2.2.4 on 2019-10-26 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_unoorder_unosite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtaBasket',
            fields=[
                ('basket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Timestamp of Creation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UnoClient')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UnoCustomer')),
            ],
            options={
                'db_table': 'PTA_BASKET',
            },
        ),
        migrations.CreateModel(
            name='PtaBasketItem',
            fields=[
                ('basket_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_id', models.UUIDField(editable=False, null=True, verbose_name='Parent Item ID')),
                ('itemcode', models.CharField(max_length=32, verbose_name='Item Code')),
                ('is_valid', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Timestamp of Creation')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.PtaBasket')),
            ],
            options={
                'db_table': 'PTA_BASKET_ITEM',
            },
        ),
        migrations.CreateModel(
            name='PtaOrderInstance',
            fields=[
                ('order_instance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Order Number')),
                ('order_name', models.CharField(default=None, max_length=32, null=True, verbose_name='Order Name')),
                ('secret', models.CharField(default=None, max_length=64, verbose_name='Order Secret')),
                ('status', models.CharField(choices=[('IN', 'Initiated'), ('IP', 'In Progress'), ('VA', 'Validated'), ('FL', 'Finalized'), ('FZ', 'Frozen'), ('EX', 'Expired'), ('VD', 'Voided')], max_length=16, verbose_name='status')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Timestamp of Creation')),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.PtaBasket')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UnoClient')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UnoCustomer')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UnoOpportunity')),
            ],
            options={
                'db_table': 'PTA_ORDER_INSTANCE',
            },
        ),
        migrations.CreateModel(
            name='PtaSite',
            fields=[
                ('pta_site_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Timestamp of Creation')),
                ('order_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.PtaOrderInstance')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.UnoSite')),
            ],
            options={
                'db_table': 'PTA_SITE',
            },
        ),
        migrations.CreateModel(
            name='PtaItemLeaf',
            fields=[
                ('leaf_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leaf_name', models.CharField(max_length=32, verbose_name='Leaf Name')),
                ('leaf_value', models.CharField(default=None, max_length=512, verbose_name='Leaf Value')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.PtaBasket')),
                ('basket_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.PtaBasketItem')),
            ],
            options={
                'db_table': 'PTA_ITEM_LEAF',
            },
        ),
        migrations.AddField(
            model_name='ptabasketitem',
            name='pta_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.PtaSite'),
        ),
    ]
