# Generated by Django 2.2.4 on 2019-11-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptabasketitem',
            name='serial',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Serial Number'),
        ),
        migrations.AddField(
            model_name='ptasite',
            name='site_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Site Name'),
        ),
    ]
