# Generated by Django 2.2.4 on 2019-11-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191103_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptabasketitem',
            name='ctg_doc_id',
            field=models.UUIDField(default=None, editable=False, verbose_name='Catalog Item ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ptabasketitem',
            name='serial',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Serial Number'),
        ),
    ]
