# Generated by Django 3.0 on 2019-12-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191130_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptabasketitem',
            name='serial',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Serial Number'),
        ),
    ]
