# Generated by Django 3.0 on 2020-01-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191227_1826'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ptapriceline',
            table='PTA_PRICE_LINE',
        ),
    ]
