# Generated by Django 2.2.3 on 2019-07-14 22:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnoCredentials',
            fields=[
                ('credentials_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Username')),
                ('password_salt', models.CharField(editable=False, max_length=8)),
                ('password_hash', models.CharField(editable=False, max_length=1024)),
                ('recovery_email', models.EmailField(help_text='Email used to reset password', max_length=254, unique=True, verbose_name='Recovery Email')),
                ('pin', models.PositiveSmallIntegerField(help_text='PIN is required to reset password', verbose_name='PIN')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UnoClient')),
            ],
            options={
                'db_table': 'UNO_CREDENTIALS',
            },
        ),
        migrations.CreateModel(
            name='UnoApproval',
            fields=[
                ('approval_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('AP', 'Approve Request'), ('DE', 'Deny Request'), ('RV', 'Revoke Business'), ('RI', 'Reinstate Business')], max_length=16, verbose_name='Action')),
                ('message', models.TextField(null=True, verbose_name='Message/Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UnoClient')),
            ],
            options={
                'db_table': 'UNO_APPROVAL',
            },
        ),
    ]
