# Generated by Django 2.2.4 on 2019-08-31 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unocustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnoOpportunity',
            fields=[
                ('opportunity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opportunity_number', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Opportunity Number')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('discount_nrc', models.CharField(choices=[('0', 'No Discount'), ('5', '5% Discount'), ('10', '10% Discount'), ('15', '15% Discount'), ('20', '20% Discount'), ('25', '25% Discount'), ('30', '30% Discount')], max_length=16, verbose_name='Non-recurring Discount')),
                ('discount_mrc', models.CharField(choices=[('0', 'No Discount'), ('5', '5% Discount'), ('10', '10% Discount'), ('15', '15% Discount'), ('20', '20% Discount'), ('25', '25% Discount'), ('30', '30% Discount')], max_length=16, verbose_name='Monthly Discount')),
                ('deal_count', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Deal Count')),
                ('deal_limit', models.PositiveSmallIntegerField(default=1, verbose_name='Deal Limit')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Timestamp of Creation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UnoClient')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UnoCustomer')),
            ],
            options={
                'db_table': 'UNO_OPPORTUNITY',
            },
        ),
    ]
