# Generated by Django 2.2.4 on 2019-11-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_unoorder_unosite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unosite',
            name='country',
            field=models.CharField(max_length=256, verbose_name='Country'),
        ),
    ]
