# Generated by Django 3.0 on 2020-01-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191119_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unoorder',
            name='data_length',
        ),
        migrations.RemoveField(
            model_name='unoorder',
            name='order_data_1',
        ),
        migrations.RemoveField(
            model_name='unoorder',
            name='order_data_2',
        ),
        migrations.RemoveField(
            model_name='unoorder',
            name='order_data_3',
        ),
        migrations.AlterField(
            model_name='unoorder',
            name='status',
            field=models.CharField(choices=[('CL', 'Cancelled'), ('SM', 'Submitted'), ('IV', 'Invalidated'), ('OD', 'Ordered'), ('CP', 'Completed')], max_length=16, verbose_name='status'),
        ),
    ]
