# Generated by Django 3.0 on 2020-01-05 19:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200101_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeevEventLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Event Time')),
                ('log_level', models.CharField(choices=[('0', 'Unknown'), ('1', 'Debug'), ('2', 'Warn'), ('3', 'Error'), ('4', 'Fatal')], editable=False, max_length=4, verbose_name='Log Level')),
                ('order_id', models.UUIDField(editable=False, null=True, verbose_name='Order ID')),
                ('user_id', models.UUIDField(editable=False, null=True, verbose_name='User ID')),
                ('log_desc', models.TextField(max_length=1024, null=True, verbose_name='Log Description')),
                ('stack_trace', models.TextField(max_length=4000, null=True, verbose_name='Stack Trace')),
            ],
            options={
                'db_table': 'SEEV_EVENT_LOG',
            },
        ),
    ]
